version: '2.2'
services:

  db:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=omnichat
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/
    networks:
      - backend
    # max_connections = 500
    command: postgres -N 500
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 40s
      timeout: 30s
      retries: 5

networks:
  backend:
    driver: bridge
volumes:
  postgres-db-data:

